### ISSUE TITLE
[feature]/support recursive type of type.

### ISSUE THREAD

**Issue by imiskolee** [vektah/gqlgen#43] opened 2018-03-08 02:34 UTC
in codegen/models_build.go:69

why not support recursive type define?

we need support it .

input is work.

```graphql
input R {
 id:Int
items:[R]
}
```

type dont work.

```graphql
type R {
 id:Int
items:[R]
}
```

**Comment by Teddy-Schmitz** [comment] 2018-03-08 08:49
to add to this it looks like the code is generating the wrong pointer type when you have the situation above.
```
		case "OR":
			var err error
			var ptr1 filters.Catalog
			rawIf2 := v.([]interface{})
			ptr1 = make([]*filters.Catalog, len(rawIf2))
			for idx2 := range rawIf2 {
				var ptr3 filters.Catalog

				ptr3, err = UnmarshalCatalogFilter(rawIf2[idx2])
				ptr1[idx2] = &ptr3
			}
			it.OR = &ptr1
			if err != nil {
				return it, err
			}
```

`var ptr1` should be a `[]*filters.Catalog`

**Comment by vektah** [comment] 2018-03-17 01:06
I need more info for this the code generated from those types look fine, perhaps a test case failing test case?

I think this might be a dupe of https://github.com/vektah/gqlgen/issues/44.

@Teddy-Schmitz I think you might have a different issue, that looks like arg unpacking (input) code, could you raise a bug with schema to reproduce it?

**Closed** 2018-03-28 09:04 UTC
Labels: bug
