### ISSUE TITLE
Strange functions on generated code

### ISSUE THREAD

**Issue by rodrigo-brito** [vektah/gqlgen#227] opened 2018-07-25 18:09 UTC
After upgrade to 0.3.0, `gqlgen` is generating strange functions on Resolver Interface:
```go
type Resolvers interface {
    // ... My resolvers

    __Directive_args(ctx context.Context, obj *introspection.Directive) ([]introspection.InputValue, error)
 
    __Field_args(ctx context.Context, obj *introspection.Field) ([]introspection.InputValue, error)
 
    __Schema_types(ctx context.Context, obj *introspection.Schema) ([]introspection.Type, error)
 
    __Schema_directives(ctx context.Context, obj *introspection.Schema) ([]introspection.Directive, error)
 
    __Type_fields(ctx context.Context, obj *introspection.Type, includeDeprecated bool) ([]introspection.Field, error)
    __Type_interfaces(ctx context.Context, obj *introspection.Type) ([]introspection.Type, error)
    __Type_possibleTypes(ctx context.Context, obj *introspection.Type) ([]introspection.Type, error)
    __Type_enumValues(ctx context.Context, obj *introspection.Type, includeDeprecated bool) ([]introspection.EnumValue, error)
    __Type_inputFields(ctx context.Context, obj *introspection.Type) ([]introspection.InputValue, error)
}
```

ResolverRoot Interface:
```go
type ResolverRoot interface {
    Mutation() MutationResolver
    Query() QueryResolver
    __Directive() __DirectiveResolver
    __Field() __FieldResolver
    __Schema() __SchemaResolver
    __Type() __TypeResolver
}

```
 In the docs and examples these fields don't exists.

**Comment by mathewbyrne** [comment] 2018-07-26 01:00
@rodrigo-brito can you provide your `schema.graphql` and `.gqlgen.yml`?  Those are all internal types that shouldn't have resolvers generated for them, so it's likely a bug somewhere.  May already be resolved in the `next` branch with the new parser.

**Comment by rodrigo-brito** [comment] 2018-07-26 01:10
I tried to reproduce it in a simple example but don't works. Sometimes it happens but not everytime.

**Comment by mathewbyrne** [comment] 2018-07-26 06:38
I suspect you might have a versioning issue with your generated code. Make sure your `gqlgen` binary matches the runtime.  If you come up with a way to reproduce, post back here.

**Closed by mathewbyrne** 2018-07-26 06:38 UTC

**Comment by yamitzky** [comment] 2018-07-29 07:58
I encountered same issue. But I cannot reproduce it with starwars example 🤔

**Comment by yamitzky** [comment] 2018-07-29 07:59
my gqlgen binary version is 0.3.0 (381b34691).

**Comment by yamitzky** [comment] 2018-07-29 08:05
schema.graphql

```graqhql
schema {
  query: Query
}

type Query {
  test: Test
}

type Test {
  test: String!
}
```

.gqlgen.yml

```yaml
schema: schema.graphql
exec:
  filename: gql/generated.go
  package: gql
model:
  filename: gql/models_gen.go
  package: gql
models:
  Test:
    model: path/to/my/package/gql.Test
```

model.go

```go
package gql

type Test struct {
	Test string
}
```

**Comment by roderm** [comment] 2023-10-31 12:51
Just had the same Issue and found my problem. In the `autobind` in the `gqlgen.yml` I included a module that contained a `Field`-struct. So instead of `introspection.Field`,  `mypackage.Field` was used. 
My fix was to just include `github.com/99designs/gqlgen/graphql/introspection` as first autobind.
