### ISSUE TITLE
Import resolver bugs.

### ISSUE THREAD

**Issue by jacklaaa89** [vektah/gqlgen#60] opened 2018-03-20 08:12 UTC
When attempting to generate code from a schema, a panic is thrown in `import_build.go` when attempting to resolve imports. The import path for my all of my types matches the `name` of one of the core imports the generated code relies on. i.e: my package: `/path/to/package/introspection` which conflicts with internal package: `github.com/vektah/gqlgen/neelance/introspection` (As they have the same base-name). I think this is down to line 40 in `import_build.go`:

`for imp := imports.findByName(localName); imp != nil && imp.Package != t.Package; localName = filepath.Base(t.Package) + strconv.Itoa(i) { ... }`

As for the example above: for the first iteration it will find match for the first iteration with the package: `github.com/vektah/gqlgen/neelance/introspection`, but will fail the `imp != nil && imp.Package != t.Package` condition. On any subsequent iteration however, the new name (i.e introspection1, ...2, ..3) will never match a package thus causing the `panic('too many collisions')` error.

**Comment by vektah** [comment] 2018-03-20 08:49
Thanks for the bug report, should be fixed now.

**Closed** 2018-03-20 08:49 UTC
Labels: bug

**Comment by jacklaaa89** [comment] 2018-03-20 08:53
Cheers for the quick resolution.

**Comment by tsuna** [comment] 2018-07-16 21:46
I seem to be experiencing this issue again (I'm using `gqlgen` built from commit 55179a61aeefeb044f023d7fa0342518b90af76e).  I have a package called `foo/query` and upon re-generating the code today I saw this:

```diff
--- a/foo/apigraphql/generated.go
+++ b/foo/apigraphql/generated.go
@@ -1,4 +1,4 @@
-// This file was generated by github.com/vektah/gqlgen, DO NOT EDIT
+// Code generated by github.com/vektah/gqlgen, DO NOT EDIT.
 
 package apigraphql
 
@@ -6,33 +6,154 @@ import (
        "bytes"
        context "context"
        apimodel "foo/apimodel"
-       query1 "foo/query"
+       query "foo/query"
        strconv "strconv"
 
        graphql "github.com/vektah/gqlgen/graphql"
        introspection "github.com/vektah/gqlgen/neelance/introspection"
-       query "github.com/vektah/gqlgen/neelance/query"
        schema "github.com/vektah/gqlgen/neelance/schema"
 )
 
```
as a result the code obviously doesn't compile anymore:
```
$ go test ./...
# foo/apigraphql
./generated.go:167:59: undefined: "foo/query".Operation
```

**Comment by tsuna** [comment] 2018-07-16 21:58
I tried going back to commit cb87a2c and still had the problem, so I went back further, to commit 40d9a11be10846d2d69c8731c503ddf434b93146, and the generated code no longer exhibits the issue and tests pass.  So I assume there has been a regression.  Re-opening.

**Comment by tsuna** [comment] 2018-07-16 22:38
Nailed it down to commits abf85a104ab1b06c6c181c7dae74d84b3d88628c / c0158f5418b679d1af358ce6f7f9a9d3ecf4fcf0 (the former doesn't build, so the last commit that works for me is a39c63a5ef9dadec023241f049d511380dbce189).
